### ISSUE TITLE
Refresh_token call failed

### ISSUE THREAD

**Issue by slafon** [Orange-OpenSource/datashare-android-lib#50]
After invalid_token error, refreshToken() is called but failed. [{"message":"MissingCredentials","description":"Full authentication is required to access this resource","code":40}]

It seems to be due to the fact the call is done with Auth Bearer header because of the authenticationApi of DatashareClient use builder passed in parameter and so has the authentication interceptor too !

**Comment by antechrestos** [comment]
Well spotted. Instead of taking a `OkHttpBuilder` as a parameter, we should either take

- a `supplier` that will be invoked for building the builder...
- a `consumer` that will  receive, if provided, each `OkHttpBuilder` that the library build
- find a way of narrowing the scope of each authenticator

Feel free to tell which solution you prefer or provide a new one. 

🍻

**Comment by antechrestos** [comment]
Should be fixed by #52 
Released in `v1.20.4`
